### ISSUE TITLE
activate/deactivate methods not fired

### ISSUE THREAD

**Issue by quasiperfect** [WPBP/WordPress-Plugin-Boilerplate-Powered#101]
the activation/deactivation functions are not called any idea why ?
the constructor is run

```
register_activation_hook(__FILE__, [ $this, 'activate' ]);
register_deactivation_hook(__FILE__, [ $this, 'deactivate' ]);
```

**Comment by Mte90** [comment]
Can you give more information? In what files there is that code? I image this one https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered/blob/master/plugin-name/includes/PN_ActDeact.php

Also this kind of line there is on your root plugin file https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered/blob/master/plugin-name/plugin-name.php#L91?

**Comment by quasiperfect** [comment]
yes just generate a plugin and place a "die" in the activate and deactivate functions. it will never be reached

**Comment by zerooverflow** [comment]
On my recent experiences, register de/activation hooks are fired from the main php files of the plugin.

**Comment by zerooverflow** [comment]
*main php file.

**Comment by quasiperfect** [comment]
i did it like this

````
require_once(D_PLUGIN_ROOT . 'composer/autoload.php');
require_once(D_PLUGIN_ROOT . 'includes/D_PostTypes.php');
require_once(D_PLUGIN_ROOT . 'public/dm_auctions.php');
require_once(D_PLUGIN_ROOT . 'includes/D_ActDeact.php');
require_once(D_PLUGIN_ROOT . 'includes/D_Uninstall.php');
require_once(D_PLUGIN_ROOT . 'public/ajax/D_Ajax.php');


register_activation_hook(__FILE__, 'activate_plugin_dm_auctions');
function activate_plugin_dm_auctions()
{
	$act = new D_ActDeact();
	$act->activate();
}


register_deactivation_hook(__FILE__, 'deactivate_plugin_dm_auctions');
function deactivate_plugin_dm_auctions()
{
	$deact = new D_ActDeact();
	$deact->deactivate();
}


add_action('admin_init', 'dm_auctions_plugin_init');
function dm_auctions_plugin_init()
{
	if (!function_exists('is_plugin_active'))
	{
		require_once(ABSPATH . '/wp-admin/includes/plugin.php');
	}

	if (!is_plugin_active('advanced-custom-fields-pro/acf.php'))
	{
		deactivate_plugins(plugin_basename(__FILE__));
	}
}
````

**Comment by zerooverflow** [comment]
And activates as external functions. Not as class method

**Comment by Mte90** [comment]
Where is that `die` that kill the execution?

**Comment by quasiperfect** [comment]
the code i posted above is the working version 

the "die"
```
private static function single_activate()
	{
die('activate');
rest of function
```

```
private static function single_deactivate()
	{
die('deactivate');
rest of function
```

**Comment by Mte90** [comment]
Ok but the code of this boilerplate doesn't contain this command: https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered/blob/master/plugin-name/includes/PN_ActDeact.php

So I don't understand what is the issue right now

**Comment by Mte90** [comment]
Ok seems that the method about activate/deactivate are never fired, but in what case? On installing the plugin? Updating? deactivating?

**Comment by quasiperfect** [comment]
i didn't get yet to update a plugin
just create -> activate -> deactivate

**Comment by Mte90** [comment]
You are right!
THere was an issue on the method that run the hooks that need the root files of the plugin and not of the files where is the code, so I fixed it the file with few improvements.

**Comment by zerooverflow** [comment]
yes, as codex reports:
register_activation_hook( $file, $function );   
$file is the path to the main plugin file inside the wp-content/plugins directory.
