### ISSUE TITLE
Composer install fails on directories with spaces 

### ISSUE THREAD

**Issue by flegfleg** [WPBP/WordPress-Plugin-Boilerplate-Powered#142]
```
😀 Composer install in progress (can require few minutes)
sh: line 0: cd: /Users/a/WorkBench/3: No such file or directory
```

path is "/Users/a/WorkBench/3 Dev/my-plugin/…"

Any quick way how to fix this? Thanks!

**Comment by Mte90** [comment]
This is the wrong repo, this is a bug of the generator https://github.com/WPBP/generator/

I will do a new release of that asap with the bugfix

**Comment by Mte90** [comment]
New release https://github.com/WPBP/generator/releases/tag/1.1.8

**Comment by flegfleg** [comment]
Hi, sorry for posting in the wrong repo and thanks a lot for the amazingly quick fix!
