### ISSUE TITLE
is_rest() not correctly checking for REST request

### ISSUE THREAD

**Issue by kentpatrick** [WPBP/WordPress-Plugin-Boilerplate-Powered#182]
Due to the plugin firing the Initialize class using action hook "plugins_loaded" the is_rest() check is coming back as false as it only checks if REST_REQUEST is defined. But this check is too early as this is not defined till the hook parse_request is fired. See below for example hook order from plugins_loaded > parse_request  :

```
plugins_loaded
sanitize_comment_cookies
setup_theme
unload_textdomain
load_textdomain
after_setup_theme
auth_cookie_malformed
auth_cookie_valid
set_current_user
init
widgets_init
register_sidebar
wp_register_sidebar_widget
wp_loaded
parse_request
```

How do I correctly check request so early in the hook order?

**Comment by Mte90** [comment]
Interesting so we need to improve the `is_rest` method maybe like this: https://github.com/turnpiece/ccluk/blob/1e5384f1da5f245f09cf9262a88b76f3414d4864/wp-content/plugins/litespeed-cache/inc/rest.cls.php#L75

**Comment by Mte90** [comment]
On https://github.com/inpsyde/wp-context/blob/main/src/WpContext.php#L102 they do in a similar way so I think that I can improve the function based on those examples.

**Comment by kentpatrick** [comment]
This is how I fixed it:

`public function is_rest() {
	if (defined('REST_REQUEST') && REST_REQUEST )
		return true;

	global $wp_rewrite;
	if ($wp_rewrite === null) $wp_rewrite = new \WP_Rewrite();

	$rest_url = wp_parse_url( trailingslashit( rest_url( ) ) );
	$current_url = wp_parse_url( add_query_arg( array( ) ) );
	return strpos( $current_url['path'], substr($rest_url['path'],0, strlen($rest_url['path'])-1)) === 0;
}`

**Comment by Mte90** [comment]
Cool do you prefer a pull request or that I integrate that change?
