### ISSUE TITLE
engine/Base.php: initialize() does not return true

### ISSUE THREAD

**Issue by gutmanl** [WPBP/WordPress-Plugin-Boilerplate-Powered#183]
Hi everyone,

in my setup, the automatically generated initialize() function of engine/Base.php looks like this:
`public function initialize() {
		$this->settings = \gsa_get_settings();
	}`
Many other functions in this boilerplate expect a non-false return value here. As the function in this form does not return anything, their checks fail, which causes them not to work. The code generator needs to be fixed to always add a return value to this function.

**Comment by Mte90** [comment]
It is very strange https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered/blob/master/plugin-name/engine/Base.php
There is no parsing of that file to remove stuff. I need to see if the issue is replicable.

**Comment by Mte90** [comment]
I tested it now and I don't see that issue.
Can yuo share the wpbp.json?
