### ISSUE TITLE
[BUG] Default WPBrowser & WPWebDriver admin password is wrong

### ISSUE THREAD

**Issue by LucasDemea** [WPBP/WordPress-Plugin-Boilerplate-Powered#197]
When running the base test suite, `$I->loginAsAdmin()` fails because admin password `password` is not the one exported in the db dump. I found that `admin` is the password used.

After changing the admin password in codeception config the test fails again for another reason : "Database Update Required" message gets prompted.

I guess the db dump needs an update.

**Comment by LucasDemea** [comment]
I must specify that I was using the db dump to populate the acceptance tests environment, and in that specific case, the default credentials were wrong. I suppose that the original expected use case is to run acceptance tests on an existing db and to customize the admin & password setting in WPBrowser & WPWebDriver sections to reflect this.
In any case, the new `dump.sql` provided in #198 allows my use case and shouldn't cause any problems.

**Comment by Mte90** [comment]
Thanks to spot this issue!
Yes the dump probably needed a DB update as it was old.
