### ISSUE TITLE
[BUG] Cron job doesn't get created

### ISSUE THREAD

**Issue by LucasDemea** [WPBP/WordPress-Plugin-Boilerplate-Powered#203]
**Describe the bug**
Cronplus job doesn't run

**To Reproduce**
1. Leave base Cron class example as it is, or add custom cron job
2. run `wp cron schedule list`
3. The cron job isn't present in scheduled jobs list

**Expected behavior**
The cron job should be created

**Additional context**
I run wpbp as a symlinked composer dependency in a local bedrock environment

**Comment by Mte90** [comment]
So I know that the class works as I am using in various projects and plugins (also with the boilerplate).
Looking at the code https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered/blob/master/plugin-name/engine/Initialize.php#L49 the cron.php is loaded everytime as it is a `integration` and cli require another call to load their files.
How it is your initialize file?

**Comment by LucasDemea** [comment]
My `Initialize.php` is the original one, with all the classes loaded.
I just checked with xdebug step debugger and the `Cron` class is loaded during Initialization.
Are you saying that it is normal that I don't see the cron job in the `wp cron schedule list` ?
Do you have a suggestion to test that the cron job is set up ?
In my case the action that I planned didn't happen, as if the cron job wasn't setup.

**Comment by Mte90** [comment]
It should be  available also on CLI, I am wondering if with a wp plugin you can see it because the other option is that the cron.php file is not loaded or something in that file.

**Comment by LucasDemea** [comment]
Ok got a bit further in my tests : the cronjob is working, but it isn't visible neither with `wp cron schedule list` nor using WP Crontrol plugin. I can see the event is triggered, but it doesn't appear in the scheduled events list

**Comment by Mte90** [comment]
Hi I tested with the basic boilerplate and the cron results inside wordpress so my guess is that there are other changes in your code of the boilerplate.

**Comment by Mte90** [comment]
Closing after 3 months of silence
