### ISSUE TITLE
[BUG] WebDriver missing

### ISSUE THREAD

**Issue by webappick** [WPBP/WordPress-Plugin-Boilerplate-Powered#217]
I am having the issue below for testing

Scenario --
  WebDriver::debugWebDriverLogs method has been called when webDriver is not set
  WebDriver::_saveScreenshot method has been called when webDriver is not set
  WebDriver::_savePageSource method has been called when webDriver is not set
  Screenshot and page source were saved into '/Users/webappick-imac-m1-pc1/Documents/sites/seoscore/wp-content/plugins/seoscore/tests/_output/' dir

**Comment by Mte90** [comment]
Do you have chromedriver or something similar?

As https://codeception.com/docs/modules/WebDriver without many tests are not executed.

**Comment by webappick** [comment]
chromedriver is install. 

Can you tell me where to configure or load webDriver?

**Comment by Mte90** [comment]
You need to execute it manually as codeception doesn't do it for you.

You can see how on https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered/blob/master/plugin-name/tests.sh#L11
