### ISSUE TITLE
[Feature] How to deploy as zip and removing the dev stuff

### ISSUE THREAD

**Issue by kamilbaranek** [WPBP/WordPress-Plugin-Boilerplate-Powered#225]
First thing first - this is awesome boilerplate, simply love it!

**Is your feature request related to a problem? Please describe.**
I managed to make 1st version of my plugin, but when I try to zip the whole plugin folder, it has more ten 70MB. 

**Describe the solution you'd like**
Since I am not so experienced in deploy stage of plugins, I'd like to ask you for some general description of the pre-production stage. I expect I will take a zip and upload it to my sites. But maybe this is too old school :)

**Additional context**
I know I should make 'yarn prod' but from there, I have no clue what next. May I remove Vendor & node_modules folders? Please provide us basic description of how to deploy you awesome plugin.

**Comment by Mte90** [comment]
To deploy a plugin you need to upload just the file you need.
As example for php you need to run `composer --no-dev update` in this way the vendor folder has just the libraries.
For node_modules you can remove it without troubles before upload it.

Usually for this developers creates their own CI or script to package a zip that does kind of things automatically.

**Comment by kamilbaranek** [comment]
Thank you very much, with your help I managed to deploy it.
