### ISSUE TITLE
[Enhancement] VS Code Integration Recommendations

### ISSUE THREAD

**Issue by MikeiLL** [WPBP/WordPress-Plugin-Boilerplate-Powered#226]
I'm looking at integrating a CS extension for VS Code.

Came across this one: https://github.com/wongjn/vscode-php-sniffer.

There are plenty to chose from.

Wondering if you have a recommendation one way or another.

If so, would be happy to draft up some docs on it.

**Comment by Mte90** [comment]
I don't use VS Code so I don't have any suggestions and it is also the reason why the project doesn't mention any, as any dev can use whatever they want for any tools.
Usually also for IDe there aren't too much that integrates the same tool like for phpcs.

**Comment by MikeiLL** [comment]
Thanks, man.
