### ISSUE TITLE
[Feature] Change/Override particular CodeatCodingStandard(s) per project

### ISSUE THREAD

**Issue by MikeiLL** [WPBP/WordPress-Plugin-Boilerplate-Powered#227]
I want to sniff for php8 and up only. Do we document how to to override that Codeat Standards in a particular project?

**Comment by Mte90** [comment]
For that you need to check the PHPCS documentation as it is to do with a ruleset.xml file

https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-Ruleset

**Comment by MikeiLL** [comment]
So, the WPBP user would make their own ruleset file and point it towards the CodeatCoding one in. the vendor dir?

**Comment by Mte90** [comment]
No you have to put it in the plugin root folder like with the other file of the same plugin.
If you see https://github.com/codeatCode/codeatcs it is just a ruleset with various rules enabled or disabled.

**Comment by MikeiLL** [comment]
So you mean, just copy that ruleset and use it, as opposed to the one in the `vendor` dir?

**Comment by Mte90** [comment]
Can be an option or you can extend COdeatCS in your ruleset with more as you can see in the phpcs documentation and the rule file you can do both.
Instead to run that CS you will use your ruleset.xml file that will have what you want. CodeatCS is just a wrapper with 3 different CS with some rules disabled.
