### ISSUE TITLE
`npm i` Can't find `assets/src/plugin-block.js`

### ISSUE THREAD

**Issue by kauaicreative** [WPBP/WordPress-Plugin-Boilerplate-Powered#229]
Here is a bug and a fix.

1. run generator after removing the `"snippet": { "backend": ["block"] ...`
2. `npm i` will throw an error trying to compile the missing `assets/src/plugin-block.js`.

commenting out 'plugin-block' in webpack.config.js fixes the issue.
```
[
	'plugin-admin',
	// 'plugin-block',
	'plugin-public',
	'plugin-settings'
]
```

**Comment by Mte90** [comment]
Did your plugin had the blocks? because probably is an issue in the generator and not in the boilerplate: https://github.com/WPBP/generator

**Comment by Mte90** [comment]
Checked the code, it is a generator bug and not in the boilerplate. We just remove the php files but not that line in the package.json.
I am working on a fix.

**Comment by Mte90** [comment]
Bug fixed in the latest release of the generator https://github.com/WPBP/generator/releases/tag/1.3.6
For the future if there are issues on the generator can you open a ticket in the right repository? just to avoid confusion for me
