### ISSUE TITLE
Potentially reconsider PN_TEXTDOMAIN

### ISSUE THREAD

**Issue by NeonArray** [WPBP/WordPress-Plugin-Boilerplate-Powered#238]
Just happened to be browsing this repo and noticed that `PN_TEXTDOMAIN` constant is used for i18n functions. As far as I understand it, this is discouraged by WordPress.

https://developer.wordpress.org/themes/functionality/internationalization/#basic-usage

> The text domain should be passed as a string to the localization functions instead of a variable. It allows parsing tools to differentiate between text domains. Example of what not to do:
> `__( 'Translate me.' , $text_domain );`

I did a quick search on the repo to see if this had been asked about or its decision documented but didn't see anything. Thought it was worth bringing it to your attention.

**Comment by Mte90** [comment]
Thanks for the thoughts.
My experience is that this is not an issue. WP-CLI used by wordpress to generate po files manage this case with no issues.
Also this case is only for for plugins that are released on the wordpress repository.
