### ISSUE TITLE
[BUG] WordPress Plugin Boilerplate Powered uses DT_TEXTDOMAIN constant in translatable string calls

### ISSUE THREAD

**Issue by dfumagalli** [WPBP/WordPress-Plugin-Boilerplate-Powered#240]
**Describe the bug**
Like several other similar boilerplates, WordPress Plugin Boilerplate Powered uses a constant (DT_TEXTDOMAIN) to specify a translation domain. However, this is considered an error by several, easily googled sources.

Translation tools will statically scan the source code and cannot run PHP code to understand what DT_TEXTDOMAIN means.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any translation string function call that allows for string translation, for example, `__( 'my text',  DT_TEXTDOMAIN )`.
2. Find DT_TEXTDOMAIN.
3. It should be a literal constant, like "mytextdomain".

**Expected behaviour**
Code to be similar to: `__( 'my text',  'mytextdomain' )`

**Additional context**
[Here are several references added to another boilerplate plugin](https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/issues/303) showing the same issue.

**Comment by Mte90** [comment]
Closing as I get no answer.
