### ISSUE TITLE
[Feature] Can we add assets/build/ to .gitignore?

### ISSUE THREAD

**Issue by ronald2wing** [WPBP/WordPress-Plugin-Boilerplate-Powered#244]
**Is your feature request related to a problem? Please describe.**
These are dynamic files; there is no reason to store them in Git. Primarily they will be generated automatically after npm install. Or they can be auto-refresh with npm run start.

**Describe the solution you'd like**
Add assets/build/ to .gitignore.

**Describe alternatives you've considered**
Add assets/build/ to .gitignore by myself.

**Additional context**
None.

**Comment by Mte90** [comment]
There is already https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered/blob/master/.gitignore#L41

Maybe it isn't changed the plugin slug on the generator?

**Comment by Mte90** [comment]
No with the generator the slug is changed, did you used the boilerplate with that?

**Comment by ronald2wing** [comment]
I see what happened. I only commit the plugin contents.
Can we also ignore it without the plugin-name since the .gitignore file is inside the plugin?

I would also like to use Composer to install the plugin from a repository (e.g., when using Bedrock and packages). How can we do that?

**Comment by Mte90** [comment]
I understand what is happening, the generator move the .gitignore so the path doens't works anymore.
I am fixing.

About composer to install the plugin in the past someone asked too but I never used bedrock or composer to install plugin.

**Comment by ronald2wing** [comment]
Thank you for your hard work!
Can we remove composer.lock from .gitignore? - *.lock

**Comment by ronald2wing** [comment]
That would be awesome. Thank you!

**Comment by Mte90** [comment]
https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered/blob/master/.gitignore as I can see the composer.lock isn't there

**Comment by ronald2wing** [comment]
*.lock will also ignore composer.lock.

**Comment by Mte90** [comment]
Implemented in the generator :-)

I am not sure when I will do a new release of the boilerplate.

**Comment by ronald2wing** [comment]
> About composer to install the plugin in the past someone asked too but I never used bedrock or composer to install plugin.

Can I open a feature request in case someone wants this feature and is capable of implementing it?

**Comment by Mte90** [comment]
Yeah sure, usually is just me working on this project so let's see.

**Comment by ronald2wing** [comment]
> Yeah sure, usually is just me working on this project so let's see.

There are so many WP developers, but very few are working on development tools.
