### ISSUE TITLE
Can't find composer folder ?

### ISSUE THREAD

**Issue by mlbd** [WPBP/WordPress-Plugin-Boilerplate-Powered#67]
Hi,

I just find your repository and It's looking really good to me but when I try to install then it's create Fatal error because of your plugin currently don't have composer folder and you already include autoload.php in your plugin.

Hope you will add autoload.php as well composer folder,

Thanks

**Comment by Mte90** [comment]
Hi mlbd, you are unlucky because I am working now on 2.0 version with composer so I have to finish all the new code and update the instructions.
To get the composer folder you have to run `compuser update` :-)
