### ISSUE TITLE
babel & Browserify ?

### ISSUE THREAD

**Issue by nabileisa** [WPBP/WordPress-Plugin-Boilerplate-Powered#70]
hi , first of all i really like what you are doing here .
i just have one question or a feature request if you might.
is there any chance you might add  babel & Browserify as alternatives to coffee script?
thanks

**Comment by Mte90** [comment]
It is not a idea but I don't have any experience for that technology sp if someone can help me it's not a problem to improve the boilerplate :-)

**Comment by Mte90** [comment]
Now wordpress use webpack and browserify is not used so much (there are alternatives).
