### ISSUE TITLE
Develop homepage

### ISSUE THREAD

**Issue by AndreaBarghigiani** [WPBP/WordPress-Plugin-Boilerplate-Powered#77]
I have developed a proposal for a new homepage of the GitHub Page for this project. We have to check all the text to be sure that they are correct. 

For this first issue I'm going to attach only the homepage, if you need plain text to adit the page I can create a Markdown document to make easy to apply modifications.
![wpbp-home](https://cloud.githubusercontent.com/assets/190159/23761746/22ab544c-04f4-11e7-8d9d-8b51eb92d178.png)

**Comment by Mte90** [comment]
amazing, maybe when there is the html version we can improve the text in few parts for more detail but i love it!

**Comment by Mte90** [comment]
I don't think that for the release of 2.1 (today) is possible to do that but I can wait for that

**Comment by AndreaBarghigiani** [comment]
Hi man, if you let me know a little earlier I could try to give the new home a little earlier but with this short notice is going to be difficult...

Anyway, I'll do my best to PR the new home in a week ;)

Have a great day.
Andrea

**Comment by Mte90** [comment]
Now the project is under opencollective so we need to add the buttons on the mockup https://opencollective.com/widgets

**Comment by AndreaBarghigiani** [comment]
I'll do it really soon!
ᐧ


Andrea Barghigiani - WordPress Fanatic/Developer/Designer
Facebook <https://www.facebook.com/andrea.barghigiani> - Twitter
<https://twitter.com/Andrea_AndMore> - LinkedIn
<https://www.linkedin.com/in/andreabarghigiani/> - YouTube
<https://www.youtube.com/channel/UCQS0bX12oFXJ_FdfEnoCTWw> - Google+
<https://plus.google.com/u/0/+AndreaBarghigiani>

*Vuoi diventare uno sviluppatore web? Ho creato un portale dedicato a te
<https://skillsandmore.org>!*


2017-09-07 12:35 GMT+02:00 Daniele Scasciafratte <notifications@github.com>:

**Comment by Mte90** [comment]
we have a repo now https://github.com/WPBP/wpbp.github.io
